[package]
name = "sitewise-code-examples"
version = "0.1.0"
authors = ["Lawrence Xiao <delonx@amazon.com>"]
edition = "2021"

# For more keys and their definitions, see https://doc.rust-lang.org/cargo/reference/manifest.html.

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-iotsitewise = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-smithy-types-convert = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = [
  "convert-chrono",
] }
tokio = { version = "1.20.1", features = ["full"] } 
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }